### ISSUE TITLE
Hard coded tickers in get_raw_data in database_upsert.rs

### ISSUE THREAD

**Issue by dbrowne** [hukasu/rust_stack_example#1]
I have a fix for this but I figured I might as well create an issue and perform a pull request with my change

**Comment by hukasu** [comment]
The intention is really just having the 2 equities (IBM and AAPL) because it is just a solution to this [exercise](https://github.com/G123-jp/python_assignment).  
Thanks though.  

Adding `Cargo.lock` to `.gitignore` is wrong here because this project outputs a executable, the comment added with it also says this.
